sudo: required
services:
  - docker

before_install:
  - docker build -t rahulguntur9/docker-react -f Dockerfile.dev . 


script:
  - docker run rahulguntur9/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-932551316013"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $Access key ID
  secret_access_key:
    secure: $Secret access key
